miopenConvolutionFwdAlgoStaticCompiledGEMM undeclared
When attempting to build op_driver for miopen the following error is received
/workspace/miopen_cudnn_ops/src/backend/op_convolution_miopen.cc:24:23: error: use of undeclared identifier 'miopenConvolutionFwdAlgoStaticCompiledGEMM'; did you mean 'miopenConvolutionFwdAlgoImplicitGEMM'?
        ALGO_CASE_STR(miopenConvolutionFwdAlgoStaticCompiledGEMM);

I can't find where miopenConvolutionFwdAlgoStaticCompiledGEMM is declared at all in miopen.  The logical step appears to be removing
it from miopen's forward algorithms.